import { IMAGES, ImageName } from "@/data/imageManifest";

/**
 * Serves the responsive WebP variants generated by scripts/optimize-images.mjs.
 *
 * Widths and intrinsic dimensions come from the generated manifest rather than
 * being passed in, so a component can never request a variant that was never
 * built — `name` is typed against the manifest, and the fallback `src` is always
 * the largest variant that actually exists on disk.
 */
export function Img({
  name,
  sizes,
  alt,
  className = "",
  priority = false,
}: {
  name: ImageName;
  /** Layout hint for the browser, e.g. "100vw" or "(max-width: 1024px) 100vw, 45vw". */
  sizes: string;
  alt: string;
  className?: string;
  /** Set on the LCP image only: eager, high priority, no lazy loading. */
  priority?: boolean;
}) {
  const { widths, width, height } = IMAGES[name];
  const largest = widths[widths.length - 1];

  return (
    <img
      src={`/Images/opt/${name}-${largest}.webp`}
      srcSet={widths.map((w) => `/Images/opt/${name}-${w}.webp ${w}w`).join(", ")}
      sizes={sizes}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? "eager" : "lazy"}
      decoding={priority ? "sync" : "async"}
      {...(priority ? { fetchpriority: "high" } : {})}
      className={className}
    />
  );
}
