#!/usr/bin/env node
/**
 * Image optimiser + manifest generator.
 *
 * Generates responsive WebP variants into public/Images/opt/ and writes
 * src/data/imageManifest.ts describing exactly which widths exist and each
 * source's true intrinsic dimensions.
 *
 * The manifest is what stops the class of bug where a component asks for a
 * 1920px variant of a 1400px-wide photograph: that variant is never generated,
 * and the <img> src pointed at a file that does not exist. Components now read
 * their widths from here rather than hardcoding them.
 *
 * Output is committed, so `sharp` is NOT a build dependency. Rerun by hand when
 * the source photographs change:
 *   npm i --no-save sharp && node scripts/optimize-images.mjs
 */
import sharp from "sharp";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = path.join(root, "public", "Images");
const outDir = path.join(srcDir, "opt");
const manifestPath = path.join(root, "src", "data", "imageManifest.ts");

/** [source file, requested widths] — widths larger than the source are skipped. */
const TARGETS = [
  ["LandingPageImage.webp", [768, 1024, 1264]],
  ["WomanWorking.webp", [480, 800, 1200]],
  ["AmenitiesOfficeBanner.jpg", [768, 1280, 1920]],
  ["Community1.webp", [480, 800, 1200]],
  ["DedicatedOffice1.webp", [480, 800, 1200]],
  ["HotDesk1.webp", [400, 800]],
  ["HostDesk4.webp", [400, 800]],
  ["HotDesk3.webp", [400, 800]],
  ["DedicatedDesk1.webp", [400, 800]],
  ["Worker1.webp", [400, 800]],
  ["DedicatedDesk3.webp", [400, 800]],
  ["PrivateOffice1.webp", [400, 800]],
  ["PrivateOffice2.webp", [400, 800]],
  ["PrivateOffice3.webp", [400, 800]],
];

await fs.mkdir(outDir, { recursive: true });

const manifest = {};

for (const [file, requested] of TARGETS) {
  const srcPath = path.join(srcDir, file);
  const base = file.replace(/\.[^.]+$/, "");
  const meta = await sharp(srcPath).metadata();

  // Never ask for a variant wider than the source — upscaling adds bytes, not detail.
  const widths = requested.filter((w) => w <= meta.width);
  if (widths.length === 0) widths.push(meta.width);

  for (const width of widths) {
    const outPath = path.join(outDir, `${base}-${width}.webp`);
    await sharp(srcPath).resize({ width, withoutEnlargement: true }).webp({ quality: 78 }).toFile(outPath);
    const after = (await fs.stat(outPath)).size;
    console.log(`  ${`${base}-${width}.webp`.padEnd(38)} ${(after / 1024).toFixed(0).padStart(4)} KB`);
  }

  const skipped = requested.filter((w) => !widths.includes(w));
  if (skipped.length) {
    console.log(`  ${"".padEnd(38)}      (source is ${meta.width}px wide — skipped ${skipped.join(", ")})`);
  }

  manifest[base] = { widths, width: meta.width, height: meta.height };
}

const body = `// GENERATED BY scripts/optimize-images.mjs — DO NOT EDIT BY HAND.
// Rerun: npm i --no-save sharp && node scripts/optimize-images.mjs

export type ImageMeta = {
  /** Variant widths that actually exist in /Images/opt/. */
  widths: number[];
  /** Intrinsic dimensions of the source, used for the width/height attributes. */
  width: number;
  height: number;
};

export const IMAGES = {
${Object.entries(manifest)
  .map(
    ([name, m]) =>
      `  ${name}: { widths: [${m.widths.join(", ")}], width: ${m.width}, height: ${m.height} },`,
  )
  .join("\n")}
} satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof IMAGES;
`;

await fs.writeFile(manifestPath, body, "utf8");
console.log(`\n  ${TARGETS.length} sources processed, manifest written to src/data/imageManifest.ts`);
