// GENERATED BY scripts/optimize-images.mjs — DO NOT EDIT BY HAND.
// Rerun: npm i --no-save sharp && node scripts/optimize-images.mjs

export type ImageMeta = {
  /** Variant widths that actually exist in /Images/opt/. */
  widths: number[];
  /** Intrinsic dimensions of the source, used for the width/height attributes. */
  width: number;
  height: number;
};

export const IMAGES = {
  LandingPageImage: { widths: [768, 1024, 1264], width: 1264, height: 848 },
  WomanWorking: { widths: [480, 800], width: 896, height: 1195 },
  AmenitiesOfficeBanner: { widths: [768, 1280], width: 1400, height: 788 },
  Community1: { widths: [480, 800, 1200], width: 1200, height: 1600 },
  DedicatedOffice1: { widths: [480, 800, 1200], width: 1600, height: 1200 },
  HotDesk1: { widths: [400, 800], width: 3024, height: 4032 },
  HostDesk4: { widths: [400, 800], width: 3024, height: 4032 },
  HotDesk3: { widths: [400, 800], width: 3024, height: 4032 },
  DedicatedDesk1: { widths: [400, 800], width: 864, height: 1184 },
  Worker1: { widths: [400, 800], width: 1200, height: 1600 },
  DedicatedDesk3: { widths: [400, 800], width: 1600, height: 1200 },
  PrivateOffice1: { widths: [400, 800], width: 3024, height: 4032 },
  PrivateOffice2: { widths: [400, 800], width: 1200, height: 1600 },
  PrivateOffice3: { widths: [400, 800], width: 1200, height: 1600 },
} satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof IMAGES;
